name: bare
version: 1.0
type: base
summary: Empty base snap for snaps that need no libc or similar.
description: |
    An empty base snap that contains nothing except the directories
    required as mount points.

parts:
  dir-layout:
    plugin: make
    source: .
